version: 2
jobs:
  jdk-8:
    working_directory: ~/github/circleci
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.11-alpine-postgis-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    parallelism: 4
    steps:
      - checkout
      - run: echo "Hello CircleCI!"
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      
  jdk-10:
    working_directory: ~/github/circleci
    docker:
      - image: circleci/openjdk:10-jdk-browsers
      - image: circleci/postgres:9.6.11-alpine-postgis-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    parallelism: 4
    steps:
      - checkout
      - run: echo "Hello CircleCI!"
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      
  jdk-11:
    working_directory: ~/github/circleci
    docker:
      - image: circleci/openjdk:11-jdk-browsers
      - image: circleci/postgres:9.6.11-alpine-postgis-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    parallelism: 4
    steps:
      - checkout
      - run: echo "Hello CircleCI!"
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      
workflows:
  version: 2
  workman:
    jobs:
      - jdk-8
      - jdk-10
      - jdk-11
